apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: kubeview   # <--- Wskazujesz namespace, który ma być ograniczony
spec:
  hard:
    # Łączne limity i requesty dla wszystkich Podów w tym namespace:
    requests.cpu: "1000m"     # Max 2 vCPU łącznie
    requests.memory: "2Gi"    # Max 2 GB RAM łącznie
    limits.cpu: "2000m"       # Max 4 vCPU w szczycie łącznie
    limits.memory: "4Gi"      # Max 8 GB RAM w szczycie łącznie

    # Opcjonalnie: limit liczby obiektów
    pods: "10"                # Max 10 Podów w tym namespace
    services: "6"             # Max 6 Serwisów