apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spring-app.fullname" . }}-config
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.datasourceUsername | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.datasourceUrl | quote }}