apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-app.fullname" . }}-secret
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.datasourcePassword | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | quote }}

